//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeckOfCards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public string CardImage { get; set; }
        public string CardValue { get; set; }
        public string CardSuit { get; set; }
        public string CardCode { get; set; }
    }
}
